### ISSUE TITLE
Error in 'tf.config.set_visible_devices' when running a Keras model in eager mode

### ISSUE THREAD

**Issue by luisoutomaior** [determined-ai/determined#1481] opened 2020-10-21 19:49 UTC
Getting the following error:

[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/experimental/keras/_tf_keras_native.py", line 77, in init
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||      master_url=master_url,
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/experimental/_native.py", line 285, in init_native
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||      master_url=master_url,
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/experimental/_native.py", line 133, in _init_cluster_mode
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||      hvd_config=load.RunpyGlobals.get_instance().hvd_config,
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/keras/_tf_keras_trial.py", line 285, in pre_execute_hook
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||      TFKerasTrialController._configure_session(env, hvd_config, session_config)
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/keras/_tf_keras_trial.py", line 265, in _configure_session
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||      tf.config.set_visible_devices(gpu, "GPU")
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||    File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||      attr = getattr(self._tfmw_wrapped_module, name)
[2020-10-21T19:34:47Z] 0c41d7e5 [RUNNING] ||  AttributeError: module 'tensorflow._api.v1.config' has no attribute 'set_visible_devices'

A possible solution is changing:
https://github.com/determined-ai/determined/blob/9d9f2c29f460f54fc230a4816accb3ab0c413f85/harness/determined/keras/_tf_keras_trial.py#L215

to:
`python
tf.config.experimental.set_visible_devices(gpu, "GPU")
`

**Comment by neilconway** [comment] 2020-11-12 20:11
Per discussion on Slack (https://determined-community.slack.com/archives/CV3MTNZ6U/p1603309124129400), I think this issue was resolved. I'll go ahead and close it, but please re-open if the problem is still occurring.

**Closed by neilconway** 2020-11-12 20:11 UTC
